Test/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from rest_framework.authtoken import views

urlpatterns = [
    #path('admin/', admin.site.urls),
    #Login
	path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'),name='login'),
	#Logout
	path('logout/', auth_views.LogoutView.as_view(template_name='registration/login.html'),name='logout'),
    # address base module
    path('base/', include('base.urls')),
    # address files module
    path('files/', include('files.urls')),
    # address users module
    path('users/', include('users.urls')),
]

urlpatterns += [
    url(r'^api/auth', include('rest_framework.urls', namespace='rest_framework'))
]

base/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from . import views

app_name = 'base'

urlpatterns = [


]

files/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from files.views import *

app_name = 'files'

urlpatterns = [
    #principal view files
    url(r'^home', FilesList.as_view() , name='home'),

]

users/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    #principal view users
    url(r'^home', views.home, name='home'),
    #new user view
    url(r'^new_user', views.create_user, name='create_user'),
    #edit user view
    url('edit_user/(?P<id_user>[0-9]+)/$', views.edit_user, name='edit_user'),
    #delete user view
    url('delete_user/(?P<id_user>[0-9]+)/$', views.delete_user, name='delete_user'),

]

base/models.py
from django.db import models

# Create your models here.

files/models.py
from django.db import models


class File(models.Model):
    document = models.FileField(upload_to="files/")
    uploaded_at = models.DateTimeField(auto_now_add=True)

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _


class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

files/forms.py
from django import forms
from files.models import File

class FileForm(forms.ModelForm):
    class Meta:
        model = File
        fields = [ 'document']

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        exclude = ['id','last_login','username' ,'is_staff', 'is_superuser','user_permissions','is_active','date_joined']
        fields = ['first_name', 'last_name', 'email','password1']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control'})
        }
        labels = {
            'first_name': ('Nombre(s)'),
            'last_name': ('Apellidos'),
            'email': ('e-mail'),
            'password1': ('Contraseña'),
        }
        help_texts = {
            'username': '',
            'is_active': '',
            'is_staff': '',
            'groups': '',
        }
    def clean_email(self):
        data = self.cleaned_data['email']
        return data.lower()


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        exclude = ['id', 'last_login', 'username', 'is_staff', 'is_superuser', 'user_permissions', 'is_active',
                   'date_joined', 'password1']
        fields = ['first_name', 'last_name', 'email']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'first_name': ('Nombre(s)'),
            'last_name': ('Apellidos'),
            'email': ('e-mail'),
        }
        help_texts = {
            'username': '',
            'is_active': '',
            'is_staff': '',
            'groups': '',
        }

    def clean_email(self):
        data = self.cleaned_data['email']
        return data.lower()

base/views.py
from django.shortcuts import render

# Create your views here.

files/views.py
from django.shortcuts import render, redirect, get_object_or_404
from files.forms import FileForm
from files.models import *
from files.serializers import *
from boto3.session import Session
from rest_framework import generics
import pandas as pd
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
import logging
import boto3
from botocore.exceptions import ClientError

# Create your views here.
class FilesList(generics.ListCreateAPIView):

    queryset = File.objects.all()
    S3_ACCESS_KEY = 'BAKIBAKI678H67HGA'
    S3_SECRET_KEY = '+vpOpILD+E9872AialendX0Ui123CKCKCKw'
    session = Session(aws_access_key_id=S3_ACCESS_KEY,
                      aws_secret_access_key=S3_SECRET_KEY)
    s3 = session.resource('s3')
    bucket = s3.Bucket('your_bucket')
    serializer_class = FileSerializer

    def get_object(self):
        queryset = self.get_queryset()
        obj = get_object_or_404(
            queryset,
            pk = self.kwargs['pk']
        )
        return obj

    @login_required(login_url='/login/')
    def home(request):
        """Principal view files"""
        for s3_file in bucket.objects.all():
            print(s3_file.key)
        if request.method == 'POST':
            form = FileForm(request.POST, request.FILES)
            data = form.cleaned_data
            f = open(data['document'], 'rb')
            if form.is_valid():
                form.save()
                #upload file
                s3_client = boto3.client('s3')
                try:
                    response = s3_client.upload_file(data['document'],bucket)
                except ClientError as e:
                    logging.error(e)
                    return False
                return redirect('/files/home')
        else:
            form = FileForm()
        return render(request, 'files.html',{'form': form, 'files': files})


    @login_required(login_url='/login/')
    def view_file(request, id_file):
        """Can view a file content"""
        file = File.objects.get(pk=id_file)
        name_file = file.document
        DataFrame = pd.read_csv(name_file)
        df = pd.DataFrame(DataFrame)
        return HttpResponse(df.to_html())


    @login_required(login_url='/login/')
    def delete_file(request, id_file):
        """Can view a file content"""
        file = File.objects.get(pk=id_file)
        file.delete()
        return redirect('/files/home')

users/views.py
from django.shortcuts import render, redirect
from users.forms import CustomUserCreationForm, CustomUserChangeForm
from users.models import *
from django.contrib.auth.decorators import login_required
# Create your views here.


@login_required(login_url='/login/')
def home(request):
    """Principal view"""
    users = CustomUser.objects.all()
    return render(request, 'users.html', {'users':users} )


@login_required(login_url='/login/')
def create_user(request):
    """Create new user"""
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()
            return redirect('/users/home')
        else:
            return render(request, 'create_user.html', {'form': form})
    else:
        form = CustomUserCreationForm()
        return render(request, 'create_user.html', {'form': form})


@login_required(login_url='/login/')
def edit_user(request, id_user):
    """Can edit a user"""
    user = CustomUser.objects.get(pk=id_user)
    if request.method == 'GET':
        form = CustomUserChangeForm(instance=user)
    else:
        form = CustomUserChangeForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            return redirect('/users/home')
    return render(request, 'edit_user.html', {'form': form})


@login_required(login_url='/login/')
def delete_user(request, id_user):
    """Can delete a user"""
    user = CustomUser.objects.get(pk=id_user)
    user.delete()
    return redirect('/users/home')

base/templates/base.html
{% load staticfiles i18n %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">


  <title>Prueba</title>
    {% block css %}
  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/modern-business.css' %}" rel="stylesheet">
    {% endblock %}
</head>

<body>

  <!-- Navigation -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="">PRUEBA</a>
    </div>
  </nav>
      <!-- Page Content -->
  <div class="container">

    <h1 class="my-4">Bienvenido</h1>
    <!-- Portfolio Section -->

    <div class="row">
      <div>
        <a class="btn btn-primary" href="{% url 'users:create_user'%}">Crear Usuario</a>
        <a class="btn btn-success" href="{% url 'files:home'%}">Archivos</a>
        <a class="btn btn-danger" href="{% url 'logout' %}">Cerrar Sesión</a>
    </div>
      <div class="col-lg-12">
        {% block content %}


        {% endblock %}

      </div>
    </div>
    <!-- /.row -->

    <hr>

  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Desarrollado por <br> David Felipe González A</p>
    </div>
    <!-- /.container -->
  </footer>
  {% block js %}
  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  {% endblock %}
</body>

</html>

files/templates/files.html
{% extends 'base.html' %}
{% block content %}

    <div class="row">
      <div class="col-md-5">
          <br>
          <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
           <div class="control-group form-group">
            <div class="controls">
              {{form}}
            </div>
          </div>
          <button type="submit">Upload</button>
        </form>
          <br>
        <table class="table">
  <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Nombre</th>
        <th scope="col">Leer</th>
        <th scope="col">Eliminar</th>
    </tr>
  </thead>
  <tbody>
    {% for file in files %}
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td>{{file.document}}</td>

        <td>
            <a class="btn btn-primary btn-sm" href="{% url 'files:view_file' file.id  %}">
                Ver
            </a>

        </td>
        <td>
           <a class="btn btn-info btn-sm" href="{% url 'files:delete_file' file.id  %}">
                Eliminar
            </a>
        </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
      </div>
    </div>
{% endblock %}

users/templates/create_user.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
      <div class="col-lg-8 mb-4">
        <h3>Nuevo Usuario</h3>
        <form name="sentMessage" id="contactForm" method="post">
          {% csrf_token %}
           <div class="control-group form-group">
            <div class="controls">
              {{form}}
            </div>
          </div>
          <button type="submit" class="btn btn-success" id="">Guardar</button>
        </form>
      </div>

    </div>
{% endblock %}

users/templates/edit_user.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
      <div class="col-lg-8 mb-4">
        <h3>Editar Usuario</h3>
        <form name="sentMessage" id="contactForm" method="post">
          {% csrf_token %}
           <div class="control-group form-group">
            <div class="controls">
              {{form}}
            </div>
          </div>
          <button type="submit" class="btn btn-success" id="">Guardar</button>
        </form>
      </div>

    </div>
{% endblock %}

users/templates/users.html
{% extends 'base.html' %}
{% block content %}
    <div class="row">
      <div class="col-md-5">
        <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nombres</th>
      <th scope="col">Apellidos</th>
        <th scope="col">Email</th>
        <th scope="col">Editar</th>
        <th scope="col">Eliminar</th>
    </tr>
  </thead>
  <tbody>
    {% for user in users %}
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td>{{user.first_name}}</td>
      <td>{{user.last_name}} </td>
      <td>{{user.email}}</td>

        <td>
            <a class="btn btn-primary btn-sm" href="{% url 'users:edit_user' user.id  %}">
                Editar
            </a>

        </td>
        <td>
           <a class="btn btn-info btn-sm" href="{% url 'users:delete_user' user.id  %}">
                Eliminar
            </a>
        </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
      </div>
    </div>
{% endblock %}